# Qubits

# Define LaTex Commands

$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}$$
$$\newcommand{\bra}[1]{\left\langle{#1}\right|}$$
$$\newcommand{\braket}[2]{\left\langle{#1}\middle|{#2}\right\rangle}$$

Resulting in:

$$\bra{\Psi}\Omega\ket{\Psi}$$

$$\braket{\Psi}{\Psi}$$

$$\braket{\frac{\Psi}{2}}{\Psi}$$

$$\bra{0}$$
$$\ket{1}$$
$$\braket{0}{1}$$

## Often $\ket{0}$ and $\ket{1}$ are represented on the vertical number line:

![](https://dpzbhybb2pdcj.cloudfront.net/kaiser/v-4/Figures/CH02_FIGxx_ket-label.png)

## They are viewed as being 180 degree rotations of each other:

![](https://dpzbhybb2pdcj.cloudfront.net/kaiser/v-4/Figures/CH02_FIGxx_rebit_NOT.png)

## If we rotate $\ket{0}$ by 90 degrees instead, we get their unitary average:

$$ \frac{ \ket{0} + \ket{1} } { \sqrt{2} } $$

## This is part of special definitions:

* +90 degree rotation: $$ \frac{ \ket{0} + \ket{1} } { \sqrt{2} } $$
* -90 degree rotation: $$ \frac{ \ket{0} - \ket{1} } { \sqrt{2} } $$

## In general:

* rotation by $\theta$: 

$$ \cos\left(\frac{\theta}{2}\right) \ket{0} + \sin\left(\frac{\theta}{2}\right) \ket{0} $$ 

## Dirac v. Numpy

In [4]:
import numpy as np
from pprint import pprint as pp

In [16]:
dirac2numpy = {
    '|0>': np.array([[1], [0]]),
    '|1>': np.array([[0], [1]]),
    '|+>': np.array([[1], [1]])/2**0.5,
    '|->': np.array([[1], [-1]])/2**0.5,
}

for k,v in dirac2numpy.items():
    print(f'\n{k} == \n{v}')


|0> == 
[[1]
 [0]]

|1> == 
[[0]
 [1]]

|+> == 
[[0.70710678]
 [0.70710678]]

|-> == 
[[ 0.70710678]
 [-0.70710678]]


## Born's rule

$$ P( \text{measurement} | \text{state} ) = 
| \braket{\text{measurement}}{\text{state}} | ^2 $$