... continue [here](https://livebook.manning.com/book/learn-quantum-computing-with-python-and-q-sharp/chapter-2/v-4/point-7622-337-337-0)

In [20]:
%run ../globals.ipynb

# Unitary operators and the Hadamard Operator

In [1]:
import numpy as np

In [2]:
ket0 = np.array(
    [[1], [0]]
)
ket0

array([[1],
       [0]])

In [3]:
ket1 = np.array(
    [[0], [1]]
)
ket1

array([[0],
       [1]])

In [4]:
ket_plus = (ket0 + ket1) / np.sqrt(2)
ket_plus

array([[0.70710678],
       [0.70710678]])

## Definition of Hadamard Operator

In [7]:
H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

In [13]:
make_pretty(H, show_brackets=True, )

In [14]:
make_pretty(H @ ket0)

In [15]:
make_pretty(H @ ket1)

In [21]:
PP %(H @ ket1)

In [23]:
X = np.array([[0, 1], [1, 0]])
PP % (X @ ket0)

In [17]:
(X @ ket0 == ket1).all()

True

In [24]:
PP % (X @ H @ ket0)